# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# mvn clean jacoco:prepare-agent install jacoco:report
name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
      - name: Build
        run: mvn -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B jacoco:prepare-agent install jacoco:report --file pom.xml
        env:
          USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
          ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Copy Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WORKOUT_HOST }}
          username: ${{ secrets.WORKOUT_USERNAME }}
          password: ${{ secrets.WORKOUT_PASSWORD }}
          source: "target/*.jar"
          target: ${{ secrets.WORKOUT_ENGINE_DIR }}
          strip_components: 1
      - name: Deploy Foundation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORKOUT_HOST }}
          username: ${{ secrets.WORKOUT_USERNAME }}
          password: ${{ secrets.WORKOUT_PASSWORD }}
          target: ${{ secrets.WORKOUT_ENGINE_DIR }}
          script:
            cd ~/foundation/ && sh deploy.sh
